volumes:
  langgraph-data:
    driver: local

services:
  langgraph-redis:
    image: redis:6
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  langgraph-postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c", "shared_preload_libraries=vector"]
    volumes:
      - langgraph-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      langgraph-postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@langgraph-postgres:5432/postgres
    command: >
      sh -c "alembic upgrade head"
    restart: "no"

  langgraph-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      langgraph-redis:
        condition: service_healthy
      langgraph-postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      REDIS_URI: redis://langgraph-redis:6379
      POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
    env_file:
      - .env.dockerfile
    healthcheck:
      test: ["CMD-SHELL", "python /api/healthcheck.py || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
